### ISSUE TITLE
KFC Party Needed.

### ISSUE THREAD

**Issue by zurez-sgig** [samkhan12/SkillGigAutomation#1]
`System.Out.println('We need KFC bucket.)`

**Comment by samkhan12** [comment]
int prad;
int true = prad sal today;
int false = prad sal tomorrow;
If (prad == true)
`System.Out.println("Today will be party")`
else if (prad == false)
`System.Out.println("Party will be cancel")`

**Comment by zurez-sgig** [comment]
Thank you for your explanation. I will open a PR with Prad and merge it.
